# create volumes from vars
- name: create volume(s) on nectar
  os_volume:
    display_name: '{{ item.vol_name }}'
    size: '{{ item.vol_size }}'
    availability_zone: '{{ availability_zone }}'
    wait: yes
    timeout: 600
    state: present
  loop: '{{ volumes }}'
  register: os_vol

# get a list of volume ids from the return value of os_volume
- name: create a list of volume ids
  set_fact:
    os_vol_ids: '{{ os_vol_ids|default([]) + [ item.id ] }}'
  loop: '{{ os_vol.results }}'

- debug:
    msg: "Volume {{ os_vol_ids }} has been created."
