- name: upload the masternode script
  become: yes
  copy: src=./masternode.sh dest=/home/ubuntu/ mode=0777

- name: execute the masternode script
  become: yes
  shell: sh /home/ubuntu/masternode.sh
