# install dependences on the host

# sudo apt-get update; sudo apt-get install python-pip
- name: install pip
  become: yes
  apt:
    name: ['python-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

# pip install --upgrade pip
- name: update pip
  become: yes
  pip:
    name: ['pip']
    state: latest

# pip install openstacksdk
- name: install openstacksdk
  become: yes
  pip:
    name: ['openstacksdk']
    state: latest  
